### ISSUE TITLE
Job: Deploy a server and compile Python client

### ISSUE THREAD

**Issue by GustavoRPS** [cjongseok/mtproto#11]
How much effort to deploy a docker or ec2 server and compile an client in python3?

**Comment by cjongseok** [comment]
@GustavoRPS I have pushed a [python client example](https://github.com/cjongseok/mtproto/tree/master/py). Please try it. 

If you also need to subscribe Telegram updates, you needs to compile proxy/tl_update.proto and integrate the generated code with the client. Please refer to [compile commands](https://github.com/cjongseok/mtproto/blob/master/compiler/build_py.sh). I think a day would be enough for you to do this.
