### ISSUE TITLE
Sending Message to User

### ISSUE THREAD

**Issue by Skyforces** [cjongseok/mtproto#13]
Hey! I like to get the full information about an user (from my contacts or not) if he writes me a message. So on `PredUpdateShortMessage`, i try to call the `UsersGetUsers` but i need an AccessHash i didnt have. how do i get it? Here is my code:
`

case *mtproto.PredUpdateShortMessage:

		{
			caller := mtproto.RPCaller{RPC: s.mconn}

			inputUser := &mtproto.TypeInputUser{
				Value: &mtproto.TypeInputUser_InputUser{
					InputUser: &mtproto.PredInputUser{
						UserId:	u.(*mtproto.PredUpdateShortMessage).Id,
						AccessHash: ???,
					},
				},
			}

			idArray := []*mtproto.TypeInputUser{
				inputUser,
			}

			_, err := caller.UsersGetUsers(context.Background(), &mtproto.ReqUsersGetUsers{
				Id: idArray,
			})

			fmt.Println(err.Error())
		}

**Comment by cjongseok** [comment]
@Skyforces Thanks for your interest in my code. You can get user hashes using ContactsGetContacts. It also needs a hash, but you can just assign 0 to it as below.
```go
caller.ContactsGetContacts(context.Background(), &mtproto.ReqContactsGetContacts{})
```
I added this example to examples/simpleshell as 'contacts' command.

**Comment by Skyforces** [comment]
Thanks for your quick reply. With your example i get all my contacts and the access hashs. It works fine but im missing Bots and foreign users, which aren't in my contact list. Maybe i understand the [getUser](https://core.telegram.org/method/users.getUsers) function wrong?

**Comment by cjongseok** [comment]
@Skyforces I think 
```go
caller.MessagesGetAllChats(context.Background(), &mtproto.ReqMessagesGetAllChats{})
```
would work for that. It returns all the chats and channels.

**Comment by Skyforces** [comment]
It works quite good so far. Still have some question, sorry i didn't clarified them. What is the function of `MessageGetChats` and `UsersGetUsers`? I thought you can get a specific User/Chat/Channel with them based on ID. Like this:

`ids := []int32{u.(*mtproto.PredUpdateShortMessage).UserId} 
chats, _ := caller.MessagesGetChats(context.Background(), &mtproto.ReqMessagesGetChats{
	Id: ids,
})`

Second is about the implementation of the [InputUser](https://core.telegram.org/type/InputUser). There are too different types, `inputUserContact` and `inputUserForeign`. One with access hash and one without. How is this implemented in your api?

**Comment by cjongseok** [comment]
@Skyforces  MessagesGetChats() needs a chat or channel ID, not an user ID. [MessagesGetAllChats()](https://github.com/cjongseok/mtproto/blob/0554ea8d55784bbac0956f632f74178f82c82229/types.tl.proto#L6571) returns [TypeMessagesChats](https://github.com/cjongseok/mtproto/blob/0554ea8d55784bbac0956f632f74178f82c82229/types.tl.proto#L328), which would be one of [PredMessagesChats](https://github.com/cjongseok/mtproto/blob/0554ea8d55784bbac0956f632f74178f82c82229/types.tl.proto#L1877) and [PredMessagesChatsSlice](https://github.com/cjongseok/mtproto/blob/0554ea8d55784bbac0956f632f74178f82c82229/types.tl.proto#L4007). The both have an array of [TypeChat](https://github.com/cjongseok/mtproto/blob/0554ea8d55784bbac0956f632f74178f82c82229/types.tl.proto#L139). TypeChat is one of [PredChat](https://github.com/cjongseok/mtproto/blob/0554ea8d55784bbac0956f632f74178f82c82229/types.tl.proto#L1433), [PredChannel](https://github.com/cjongseok/mtproto/blob/0554ea8d55784bbac0956f632f74178f82c82229/types.tl.proto#L3055), ... . PredChat and PredChannel have an id, and you can use it for MessagesGetChats().

Now InputUser has no types of inputUserContact and inputUserForeign. Telegram's mtproto document is too old, so you should refer to the protocol definition in [this protobuf file](https://github.com/cjongseok/mtproto/blob/0554ea8d55784bbac0956f632f74178f82c82229/types.tl.proto#L28); Telegram's document version is layer 23, the latest one is [layer 81](https://github.com/telegramdesktop/tdesktop/blob/bf775cb4ca67ab2c36082b20817bfbcd44379f26/Telegram/Resources/scheme.tl#L1295), and mine is 71.

**Comment by Skyforces** [comment]
Okay, I undestand this now. You pushed me to the right point. Thank you! Keep on your good work!
