### ISSUE TITLE
Changing DC?

### ISSUE THREAD

**Issue by FedorZaytsev** [cjongseok/mtproto#18]
In order to download something from telegram servers, I sometimes need to change datacenter (error "mtproto RPC error: 303 FILE_MIGRATE_2 " if you are interested why). How can I do it with your lib? As far as I understand I have no option to get "dcOptions" field from Session struct which contains all the information about available DCs, because it is a private field and apiDcOption(...) is private too. 

Can you please provide any way either to get "dcOptions" or to reconnect to the specific DC? The second way is a little bit harder because it will require to first call AuthExportAuthorization, reconnect to new dc and then call AuthImportAuthorization.

P.S. Thanks for the project and really great support. I can do a merge request if you are busy

**Comment by cjongseok** [comment]
Can you try this commit? it is in migrate_session branch

**Comment by FedorZaytsev** [comment]
It looks like that this branch works. Can you merge it into master?
