### ISSUE TITLE
An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by 0lightbee0** [cjongseok/mtproto#6]
2018/02/22 13:55:00 MAIN: load authentication
2018/02/22 13:55:00 [MM 1855813799] start
2018/02/22 13:55:00 [MM 1855813799] loadsession of  +86***
2018/02/22 13:55:00 [MM 1855813799] connect failure: Cannot Load Session info from neither session file nor env: open new session:%!(EXTRA *errors.errorString=New session)
2018/02/22 13:55:00 Cannot Load Session info from neither session file nor env: open new session:%!(EXTRA *errors.errorString=New session)
2018/02/22 13:55:08 MAIN: new authentication
2018/02/22 13:55:08 [MM 1161534771] start
2018/02/22 13:55:08 [MM 1161534771] newsession to  149.154.167.50:443
2018/02/22 13:55:08 [0-196229755453559639] dial TCP to 149.154.167.50:443
2018/02/22 13:55:09 [MM 1161534771] connect failure: write tcp 192.168.0.107:57004->149.154.167.50:443: wsasend: An existing connection was forcibly closed by the remote host.
2018/02/22 13:55:09 write tcp 192.168.0.107:57004->149.154.167.50:443: wsasend: An existing connection was forcibly closed by the remote host.

**Comment by cjongseok** [comment]
what's your code and environment?

**Comment by 0lightbee0** [comment]
![image](https://user-images.githubusercontent.com/19899022/36522897-f10c5c20-17d9-11e8-9143-bd9144b930dc.png)
![image](https://user-images.githubusercontent.com/19899022/36522913-007fa7e8-17da-11e8-8cfd-5afd0168c56d.png)

**Comment by cjongseok** [comment]
Can you try it again after removing ${HOME}/.telegram_*** file?

**Comment by 0lightbee0** [comment]
yes,i tried.This is the result of the trial.

**Comment by cjongseok** [comment]
oh sorry, please try it again after setting sessionFileHome = ""

**Comment by cjongseok** [comment]
are you in China?

**Comment by 0lightbee0** [comment]
Yes.

**Comment by cjongseok** [comment]
Then can you try it over VPN?

**Comment by 0lightbee0** [comment]
Do you mean that I was blocked by a firewall?

**Comment by cjongseok** [comment]
I think so.
There is a case which an application encountered "the connection was forcibly closed" in China but VPN thru Hong Kong.

**Comment by 0lightbee0** [comment]
Well, I see. Thank you for your answer.

**Comment by cjongseok** [comment]
It's my pleasure. If you try it over VPN, please share the result then other guys can refer it.
Thank you :)

**Comment by 0lightbee0** [comment]
I will.

**Comment by 0lightbee0** [comment]
But it's strange that I was successful when I Ping the remote host.

**Comment by 0lightbee0** [comment]
Maybe you should add the capability to use a proxy? For example, socks5.

**Comment by cjongseok** [comment]
Can you check the port 443 is reachable from your PC?
On Windows, you can use telnet. see https://www.acronis.com/en-us/articles/telnet/

Unfortunately, I have no plan to add socks5, sorry. I hope VPN would work.
If you really need socks5 with mtproto, it seems [this open pull request](https://github.com/sdidyk/mtproto/pull/5/files) to [sdidyk/mtproto](https://github.com/sdidyk/mtproto) can be a good start.

**Comment by 0lightbee0** [comment]
It was true that I was blocked by the firewall, and finally I solved this problem when I used the Socks5 agent.
